#include "c_plus_plus.h"

C_Plus_Plus::C_Plus_Plus()
{
    this->keywordPatterns   <<"\\bAsm\\b"
                            << "\\bauto\\b"
                            <<"\\bchar\\b"
                            <<"\\bbreak\\b"
                            <<"\\bcase\\b"
                            <<"\\bcatch\\b"
                            <<"\\bcontinue\\b"
                            << "\\bclass\\b"
                            << "\\bconst\\b"
                            << "\\bdouble\\b"
                            <<"\\bdefault\\b"
                            <<"\\bdelete\\b"
                            <<"\\bdo\\b"
                            << "\\benum\\b"
                            <<"\\bdynamic_cast\\b"
                            <<"\\bfalse\\b"
                            <<"\\bfloat\\b"
                            << "\\bexplicit\\b"
                            <<"\\bextern\\b"
                            << "\\bfriend\\b"
                            << "\\binline\\b"
                            <<"\\bmutable\\b"
                            << "\\bint\\b"
                            << "\\blong\\b"
                            << "\\bnamespace\\b"
                            << "\\boperator\\b"
                            << "\\bprivate\\b"
                            << "\\bprotected\\b"
                            <<"\\bthrow\\b"
                            << "\\bpublic\\b"
                            << "\\bshort\\b"
                            <<"\\btrue\\b"
                            << "\\bsignals\\b"
                            <<"\\bnew\\b"
                            <<"\\btry\\b"
                            << "\\bsigned\\b"
                            << "\\bslots\\b"
                            << "\\bstatic\\b"
                            <<"\\bstatic_cast\\b"
                            << "\\bstruct\\b"
                            << "\\btemplate\\b"
                            <<"\\bregister\\b"
                            << "\\btypedef\\b"
                            <<"\\btypeid\\b"
                            << "\\btypename\\b"
                            <<"\\bswitch\\b"
                            << "\\bunion\\b"
                            << "\\bunsigned\\b"
                            <<"\\busing\\b"
                            <<"\\bgoto\\b"
                            << "\\bvirtual\\b"
                            << "\\bvoid\\b"
                            <<"\\bwcahr_t\\b"
                            << "\\bvolatile\\b"
                            <<"\\breinterpret_cast\\b"
                            << "\\bif\\b"
                            <<"\\breturn\\b"
                            <<"\\bsizeof\\b"
                            << "\\belse\\b"
                            << "\\bwhile\\b"
                            <<"\\bthis\\b"
                            << "\\bfor\\b"
                            << "\\bbool\\b";
    this->commentStartExpression = QRegularExpression("/\\*");
    this->commentEndExpression = QRegularExpression("\\*/");
    this->singleLineComment="//";
}

