#include "javascript.h"

JavaScript::JavaScript()
{
    this->keywordPatterns   <<"\\bbreak\\b"
                            <<"\\bcase\\b"
                            <<"\\bcatch\\b"
                            <<"\\bcontinue\\b"
                            <<"\\bdebugger\\b"
                            <<"\\bdefault\\b"
                            <<"\\bdelete\\b"
                            <<"\\bdo\\b"
                            <<"\\belse\\b"
                            <<"\\bfinally\\b"
                            <<"\\bfor\\b"
                            <<"\\bfuntion\\b"
                            <<"\\bif\\b"
                            <<"\\bin\\b"
                            <<"\\binstanceof\\b"
                            <<"\\bnew\\b"
                            <<"\\breturn\\b"
                            <<"\\bswitch\\b"
                            <<"\\bthis\\b"
                            <<"\\bthrow\\b"
                            <<"\\btry\\b"
                            <<"\\btypeof\\b"
                            <<"\\bvar\\b"
                            <<"\\bvoid\\b"
                            <<"\\bwhile\\b"
                            <<"\\bwith\\b"
                            <<"\\bclass\\b"
                            <<"\\bconst\\b"
                            <<"\\benum\\b"
                            <<"\\bexport\\b"
                            <<"\\bextends\\b"
                            <<"\\bimport\\b"
                            <<"\\bsuper\\b"
                            <<"\\bimplements\\b"
                            <<"\\binterface\\b"
                            <<"\\blet\\b"
                            <<"\\bpackage\\b"
                            <<"\\bprivate\\b"
                            <<"\\bprotected\\b"
                            <<"\\bpublic\\b"
                            <<"\\bstatic\\b"
                            <<"\\byield\\b"
                            <<"\\bnull\\b"
                            <<"\\btrue\\b"
                            <<"\\bfalse\\b"
                            <<"\\bint\\b"
                            <<"\\bbyte\\b"
                            <<"\\bchar\\b"
                            <<"\\bgoto\\b"
                            <<"\\blong\\b"
                            <<"\\bfinal\\b"
                            <<"\\bfloat\\b"
                            <<"\\bshort\\b"
                            <<"\\bdouble\\b"
                            <<"\\bnative\\b"
                            <<"\\bthrows\\b"
                            <<"\\bboolean\\b"
                            <<"\\babstract\\b"
                            <<"\\bvolatile\\b"
                            <<"\\btransient\\b"
                            <<"\\bsynchronized\\b";
    this->commentStartExpression = QRegularExpression("/\\*");
    this->commentEndExpression = QRegularExpression("\\*/");
    this->singleLineComment= "//";

}
